### ISSUE TITLE
Auth0 pagination issue - can go to next page when no more results

### ISSUE THREAD

**Issue by simoneb** [nearform/brokeneck#27]
This applies to both users and groups, there must be something wrong with the server side logic.

### Behavior

When there are, say, 4 records in total, and page size is 2, you can go to page 2 (showing records 3 and 4) but you can also go to the next page 3, which won't show any records. 

### Expectation

It should not be possible to go to page 3 when there are in total 4 records and page size is 2

**Comment by RudyRed** [comment]
Auth0 is addressed as part of #24
