### ISSUE TITLE
document peer dependencies needed when using the react package standalone

### ISSUE THREAD

**Issue by simoneb** [nearform/brokeneck#42]
There are a few peer deps needed, make sure they're documented in the usage section

**Comment by ekynoxe** [comment]
Current peer dependencies for brokeneck-react are as follows:

    "@material-ui/core": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.57",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0"


Is it just a matter of adding this list in the documentation under "Usage > As a React component"?
Do we need to mention the versions, or just the packages?

**Comment by simoneb** [comment]
@ekynoxe replied in the PR
