### ISSUE TITLE
Clear "add user to group" input field crashes application

### ISSUE THREAD

**Issue by ekynoxe** [nearform/brokeneck#45]
Reproduction steps:

- Go to an individual group page
- Open the "Add Users" dialogue
- Select a user in the drop down
- Clear the input either by deleting the text with the keyboard OR clicking on the cross icon
- Error `TypeError: Cannot read property 'Username' of null` appears

This does not happen with the "add to group" functionality from a single user page.
Perhaps because the input on this screen is not a searchable field.

![Screenshot 2021-01-07 at 10 14 36](https://user-images.githubusercontent.com/154017/103880946-b3364f80-50d1-11eb-8d1d-645d5101f76e.png)
![Screenshot 2021-01-07 at 10 14 11](https://user-images.githubusercontent.com/154017/103880948-b3cee600-50d1-11eb-8279-f065b4e86030.png)

**Comment by simoneb** [comment]
fixed in #64
